In [2]:
import pandas as pd
import numpy as np

In [3]:
# Import raw data
cars = pd.read_csv('all_car_adverts.csv')

In [4]:
# Keep rows with genuine year values
cars_clean = cars.loc[ cars.year.str[0:2].isin(['19','20']) ]

In [5]:
# Cars with missing miles don't have mileage in the specs (some have "1 mile" but that is clearly incorrect). Drop these rows.
with pd.option_context('display.max_colwidth', None):
    print(cars_clean.loc[(cars_clean.miles.isna()) & (cars_clean.car_specs.str.contains('1 mile')),['car_specs','miles']])

                                                                      car_specs  \
4375           2022 (72 reg), SUV, 1 mile, 2.9L, 510PS, Automatic, Petrol, ULEZ
4817           2022 (72 reg), SUV, 1 mile, 2.9L, 510PS, Automatic, Petrol, ULEZ
4921    2022 (72 reg), SUV, 1 mile, 1.5L, 160PS, Automatic, Petrol Hybrid, ULEZ
4927    2022 (72 reg), SUV, 1 mile, 1.5L, 160PS, Automatic, Petrol Hybrid, ULEZ
4957    2022 (72 reg), SUV, 1 mile, 1.5L, 160PS, Automatic, Petrol Hybrid, ULEZ
...                                                                         ...
733680   2022 (22 reg), SUV, 1 mile, 1.2L, 130PS, Manual, Petrol, 1 owner, ULEZ
734393            2022 (22 reg), SUV, 1 mile, 1.2L, 130PS, Manual, Petrol, ULEZ
734412   2022 (22 reg), SUV, 1 mile, 1.2L, 130PS, Manual, Petrol, 1 owner, ULEZ
788197         2022 (22 reg), SUV, 1 mile, 1.5L, 150PS, Automatic, Petrol, ULEZ
791479         2022 (22 reg), SUV, 1 mile, 1.5L, 150PS, Automatic, Petrol, ULEZ

        miles
4375      NaN
4817      NaN
4921      NaN
4927      NaN
4957      NaN
...       ...
733680    NaN
734393    NaN
734412    NaN
788197    NaN
791479    NaN

[144 rows x 2 columns]

In [6]:
# Remove cars with missing mileage data
cars_clean = cars_clean.dropna(subset=['miles'])

In [7]:
cars_clean.loc[(cars_clean.model.isna()),['car_title','make','model']]

               car_title     make model
6               AC Cobra       AC   NaN
7               AC Cobra       AC   NaN
5140         Alpine A110   Alpine   NaN
5154         Alpine A110   Alpine   NaN
5155         Alpine A110   Alpine   NaN
...                  ...      ...   ...
612043  REO Flying Cloud      Reo   NaN
612045     Replica Cobra  Replica   NaN
649955      Shelby Cobra   Shelby   NaN
654124    Sunbeam Alpine  Sunbeam   NaN
818454  Yamaha YXZ 1000R   Yamaha   NaN

[222 rows x 3 columns]

In [8]:
# Function to retrieve model from car title by removing the make and the space after it
def model_from_title(row):
    if pd.notnull(row.car_title) and pd.notnull(row.make):
        return row.car_title[len(row.make)+1:]
    return np.nan

# Fill in any missing model values using the car title  
cars_clean.model = cars_clean.model.fillna(cars_clean.apply(model_from_title, axis=1))

In [9]:
# No missing makes or models
cars_clean.loc[(cars_clean.model.isna()) & (cars_clean.make.isna())]

Empty DataFrame
Columns: [Unnamed: 0, make, model, variant, car_price, car_badges, car_title, car_sub_title, car_attention_grabber, car_specs, car_seller, car_seller_rating, car_seller_location, year, reg, body_type, miles, engine_vol, engine_size, engine_size_unit, transmission, feul_type, num_owner, ulez, full_service, part_service, part_warranty, full_dealership, first_year_road_tax, brand_new, finance_available, discounted]
Index: []

[0 rows x 32 columns]

In [10]:
# correct spelling error in column name
cars_clean.rename(columns = {'feul_type':'fuel_type'}, inplace = True)

In [11]:
# Save clean data so that the model can access it
cars_clean.to_csv('cars_clean.csv', index=False)