In [1]:
import pandas as pd
import numpy as np

In [2]:
# Import raw data
cars = pd.read_csv('all_car_adverts.csv')

In [4]:
# Keep rows with genuine year values
cars_clean = cars.loc[ cars.year.str[0:2].isin(['19','20']) ]

In [5]:
# Cars with missing miles don't have mileage in the specs (some have "1 mile" but that is clearly incorrect). Drop these rows.
with pd.option_context('display.max_colwidth', None):
    print(cars_clean.loc[(cars_clean.miles.isna()) & (cars_clean.car_specs.str.contains('1 mile')),['car_specs','miles']])

                                                                      car_specs  \
4375           2022 (72 reg), SUV, 1 mile, 2.9L, 510PS, Automatic, Petrol, ULEZ
4817           2022 (72 reg), SUV, 1 mile, 2.9L, 510PS, Automatic, Petrol, ULEZ
4921    2022 (72 reg), SUV, 1 mile, 1.5L, 160PS, Automatic, Petrol Hybrid, ULEZ
4927    2022 (72 reg), SUV, 1 mile, 1.5L, 160PS, Automatic, Petrol Hybrid, ULEZ
4957    2022 (72 reg), SUV, 1 mile, 1.5L, 160PS, Automatic, Petrol Hybrid, ULEZ
...                                                                         ...
733680   2022 (22 reg), SUV, 1 mile, 1.2L, 130PS, Manual, Petrol, 1 owner, ULEZ
734393            2022 (22 reg), SUV, 1 mile, 1.2L, 130PS, Manual, Petrol, ULEZ
734412   2022 (22 reg), SUV, 1 mile, 1.2L, 130PS, Manual, Petrol, 1 owner, ULEZ
788197         2022 (22 reg), SUV, 1 mile, 1.5L, 150PS, Automatic, Petrol, ULEZ
791479         2022 (22 reg), SUV, 1 mile, 1.5L, 150PS, Automatic, Petrol, ULEZ

        miles
4375      NaN
4817      NaN
4921      NaN
4927      NaN
4957      NaN
...       ...
733680    NaN
734393    NaN
734412    NaN
788197    NaN
791479    NaN

[144 rows x 2 columns]

In [6]:
# Remove cars with missing mileage data
cars_clean = cars_clean.dropna(subset=['miles'])

In [7]:
cars_clean.loc[(cars_clean.model.isna()),['car_title','make','model']]

               car_title     make model
6               AC Cobra       AC   NaN
7               AC Cobra       AC   NaN
5140         Alpine A110   Alpine   NaN
5154         Alpine A110   Alpine   NaN
5155         Alpine A110   Alpine   NaN
...                  ...      ...   ...
612043  REO Flying Cloud      Reo   NaN
612045     Replica Cobra  Replica   NaN
649955      Shelby Cobra   Shelby   NaN
654124    Sunbeam Alpine  Sunbeam   NaN
818454  Yamaha YXZ 1000R   Yamaha   NaN

[222 rows x 3 columns]

In [8]:
# Function to retrieve model from car title by removing the make and the space after it
def model_from_title(row):
    if pd.notnull(row.car_title) and pd.notnull(row.make):
        return row.car_title[len(row.make)+1:]
    return np.nan

# Fill in any missing model values using the car title  
cars_clean.model = cars_clean.model.fillna(cars_clean.apply(model_from_title, axis=1))

In [9]:
# No missing makes or models
cars_clean.loc[(cars_clean.model.isna()) & (cars_clean.make.isna())]

Empty DataFrame
Columns: [Unnamed: 0, make, model, variant, car_price, car_badges, car_title, car_sub_title, car_attention_grabber, car_specs, car_seller, car_seller_rating, car_seller_location, year, reg, body_type, miles, engine_vol, engine_size, engine_size_unit, transmission, feul_type, num_owner, ulez, full_service, part_service, part_warranty, full_dealership, first_year_road_tax, brand_new, finance_available, discounted]
Index: []

[0 rows x 32 columns]

In [10]:
# correct spelling error in column name
cars_clean.rename(columns = {'feul_type':'fuel_type'}, inplace = True)

In [11]:
# Save clean data so that the model can access it
cars_clean.to_csv('cars_clean.csv', index=False)

In [62]:
cars_clean = pd.read_csv('cars_clean.csv')

In [63]:
cars_clean.make.unique()

array(['AC', 'Abarth', 'Aixam', 'Ak', 'Alfa Romeo', 'Alpine', 'Alvis',
       'Ariel', 'Aston Martin', 'Audi', 'Austin', 'BMW', 'Bac',
       'Beauford', 'Bentley', 'Bowler', 'Bugatti', 'Buick', 'Cadillac',
       'Caterham', 'Chesil', 'Chevrolet', 'Chrysler', 'Citroen',
       'Corvette', 'Crendon', 'Cupra', 'DFSK', 'DS AUTOMOBILES', 'Dacia',
       'Daewoo', 'Daf', 'Daihatsu', 'Daimler', 'Datsun', 'Dax',
       'De Tomaso', 'Dodge', 'Factory Five', 'Ferrari', 'Fiat', 'Ford',
       'GMC', 'Gardener', 'Gbs', 'Genesis Motor', 'Great Wall', 'Honda',
       'Hummer', 'Hyundai', 'Infiniti', 'Isuzu', 'Iveco', 'JBA', 'Jaguar',
       'Jeep', 'Jensen', 'KTM', 'Kia', 'LEVC', 'Lada', 'Lamborghini',
       'Lancia', 'Land Rover', 'Lexus', 'Leyland', 'Lincoln', 'Locust',
       'London Taxis International', 'Lotus', 'MEV', 'MG', 'MINI',
       'Marcos', 'Maserati', 'Maxus', 'Maybach', 'Mazda', 'McLaren',
       'Mercedes-Benz', 'Microcar', 'Mitsubishi', 'Moke', 'Morgan',
       'Morris', 'NG', 'Nissan', 'Noble', 'Oldsmobile', 'Panther',
       'Perodua', 'Peugeot', 'Piaggio', 'Pilgrim', 'Polaris', 'Polestar',
       'Pontiac', 'Porsche', 'Proton', 'Radical', 'Reliant', 'Renault',
       'Reo', 'Replica', 'Riley', 'Robin Hood', 'Rolls-Royce', 'Rover',
       'Royale', 'SEAT', 'SKODA', 'Saab', 'Shelby', 'Smart', 'Ssangyong',
       'Subaru', 'Sunbeam', 'Suzuki', 'TVR', 'Tesla', 'Tiger', 'Toyota',
       'Triumph', 'Ultima', 'Vauxhall', 'Volkswagen', 'Volvo',
       'Westfield', 'Wolseley', 'Yamaha', 'Zimmer'], dtype=object)

In [64]:
cazoocars = pd.read_csv('dataScraping/cazoo2_data.csv')

In [65]:
cazoocars

                 Title    Price  Year          Miles    Fuel
0          Ford Mondeo   £1,295  2010  171,000 miles  Diesel
1          Ford Fiesta   £1,000  2010   98,000 miles  Petrol
2      Volkswagen Golf     £995  2006  116,500 miles  Diesel
3         Renault Clio   £1,195  2010   78,000 miles  Petrol
4          Skoda Rapid   £1,495  2013  136,157 miles  Diesel
...                ...      ...   ...            ...     ...
93405     Peugeot 2008   £6,495  2014   55,000 miles  Petrol
93406    Jaguar F-Pace   £9,495  2016  109,000 miles  Diesel
93407       Volvo XC60   £7,795  2013  127,810 miles  Diesel
93408          Audi A3  £10,900  2019   78,587 miles  Petrol
93409  MINI Countryman  £11,995  2018   61,000 miles  Diesel

[93410 rows x 5 columns]

In [66]:
cazoocars.Price = cazoocars.Price.str.replace('£','').str.replace(',','').astype(float)

In [67]:
cazoocars.Miles = cazoocars.Miles.str.replace(' miles','')
cazoocars.Miles = cazoocars.Miles.str.replace(' mile','')
cazoocars.Miles = cazoocars.Miles.str.replace(',','').astype(float)

In [68]:
cazoocars['Make'] = cazoocars.Title

In [69]:
makes = cars_clean.make.unique()
makes = np.append(makes, ['Skoda','smart', 'DS Automobiles','KGM', 'INEOS', 'GWM', 'BYD', 'Leapmotor','Humber', 'Hillman', 'Geely', 'Omoda', 'Chery', 'Genesis', 'Jaecoo', 'Skywell', 'Fisker', 'Genesis', 'Opel'])
makes

array(['AC', 'Abarth', 'Aixam', 'Ak', 'Alfa Romeo', 'Alpine', 'Alvis',
       'Ariel', 'Aston Martin', 'Audi', 'Austin', 'BMW', 'Bac',
       'Beauford', 'Bentley', 'Bowler', 'Bugatti', 'Buick', 'Cadillac',
       'Caterham', 'Chesil', 'Chevrolet', 'Chrysler', 'Citroen',
       'Corvette', 'Crendon', 'Cupra', 'DFSK', 'DS AUTOMOBILES', 'Dacia',
       'Daewoo', 'Daf', 'Daihatsu', 'Daimler', 'Datsun', 'Dax',
       'De Tomaso', 'Dodge', 'Factory Five', 'Ferrari', 'Fiat', 'Ford',
       'GMC', 'Gardener', 'Gbs', 'Genesis Motor', 'Great Wall', 'Honda',
       'Hummer', 'Hyundai', 'Infiniti', 'Isuzu', 'Iveco', 'JBA', 'Jaguar',
       'Jeep', 'Jensen', 'KTM', 'Kia', 'LEVC', 'Lada', 'Lamborghini',
       'Lancia', 'Land Rover', 'Lexus', 'Leyland', 'Lincoln', 'Locust',
       'London Taxis International', 'Lotus', 'MEV', 'MG', 'MINI',
       'Marcos', 'Maserati', 'Maxus', 'Maybach', 'Mazda', 'McLaren',
       'Mercedes-Benz', 'Microcar', 'Mitsubishi', 'Moke', 'Morgan',
       'Morris', 'NG', 'Nissan', 'Noble', 'Oldsmobile', 'Panther',
       'Perodua', 'Peugeot', 'Piaggio', 'Pilgrim', 'Polaris', 'Polestar',
       'Pontiac', 'Porsche', 'Proton', 'Radical', 'Reliant', 'Renault',
       'Reo', 'Replica', 'Riley', 'Robin Hood', 'Rolls-Royce', 'Rover',
       'Royale', 'SEAT', 'SKODA', 'Saab', 'Shelby', 'Smart', 'Ssangyong',
       'Subaru', 'Sunbeam', 'Suzuki', 'TVR', 'Tesla', 'Tiger', 'Toyota',
       'Triumph', 'Ultima', 'Vauxhall', 'Volkswagen', 'Volvo',
       'Westfield', 'Wolseley', 'Yamaha', 'Zimmer', 'Skoda', 'smart',
       'DS Automobiles', 'KGM', 'INEOS', 'GWM', 'BYD', 'Leapmotor',
       'Humber', 'Hillman', 'Geely', 'Omoda', 'Chery', 'Genesis',
       'Jaecoo', 'Skywell', 'Fisker', 'Genesis', 'Opel'], dtype=object)

In [70]:

def make_from_title(row):
    for make in makes:
        if row[0:len(make)] == make:
            return make
    return 'Unknown'
cazoocars['Make'] = cazoocars['Make'].map(make_from_title)

In [71]:
cazoocars.loc[cazoocars.Make == 'Unknown'].Title.unique()

array([], dtype=object)

In [ ]:
def model_from_title(row):
    return row[len(row.Make)+1:]

                 Title    Price  Year     Miles    Fuel        Make
0          Ford Mondeo   1295.0  2010  171000.0  Diesel        Ford
1          Ford Fiesta   1000.0  2010   98000.0  Petrol        Ford
2      Volkswagen Golf    995.0  2006  116500.0  Diesel  Volkswagen
3         Renault Clio   1195.0  2010   78000.0  Petrol     Renault
4          Skoda Rapid   1495.0  2013  136157.0  Diesel       Skoda
...                ...      ...   ...       ...     ...         ...
93405     Peugeot 2008   6495.0  2014   55000.0  Petrol     Peugeot
93406    Jaguar F-Pace   9495.0  2016  109000.0  Diesel      Jaguar
93407       Volvo XC60   7795.0  2013  127810.0  Diesel       Volvo
93408          Audi A3  10900.0  2019   78587.0  Petrol        Audi
93409  MINI Countryman  11995.0  2018   61000.0  Diesel        MINI

[93410 rows x 6 columns]

In [75]:
cazoocars['Model'] = cazoocars['Title'].str[len(cazoocars['Make'])+1:len(cazoocars['Title'])]

In [87]:
cazoocars.iloc[5].Title[len(cazoocars.iloc[5].Make)+1:]

'Mondeo'

In [88]:
def model_from_title(row):
    return row.Title[len(row.Make)+1:]

In [90]:
cazoocars['Model'] =cazoocars.apply(model_from_title, axis=1)

In [97]:
cazoocars = cazoocars.rename(columns = {'Price':'car_price', 'Year':'year', 'Miles':'miles', 'Make':'make', 'Model':'model', 'Fuel':'fuel_type'})

In [98]:
cazoocars.to_csv('cazoocarsclean.csv', index=False)

,Title,Price,Year,Miles,Fuel,Make,Model
0,Ford Mondeo,1295.0,2010,171000.0,Diesel,Ford,Mondeo
1,Ford Fiesta,1000.0,2010,98000.0,Petrol,Ford,Fiesta
2,Volkswagen Golf,995.0,2006,116500.0,Diesel,Volkswagen,Golf
3,Renault Clio,1195.0,2010,78000.0,Petrol,Renault,Clio
4,Skoda Rapid,1495.0,2013,136157.0,Diesel,Skoda,Rapid
...,...,...,...,...,...,...,...
93405,Peugeot 2008,6495.0,2014,55000.0,Petrol,Peugeot,2008
93406,Jaguar F-Pace,9495.0,2016,109000.0,Diesel,Jaguar,F-Pace
93407,Volvo XC60,7795.0,2013,127810.0,Diesel,Volvo,XC60
93408,Audi A3,10900.0,2019,78587.0,Petrol,Audi,A3
93409,MINI Countryman,11995.0,2018,61000.0,Diesel,MINI,Countryman